---
name: Build

on: pull_request

jobs:
  build:
    permissions:
      contents: read
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@27afc57310de0aca22e01e4e34e51b84a75063e9 # 1.6.0
    with:
      tag: latest-actions-build
    secrets: inherit
