---
name: Build Tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-docker.yml
    with:
      tag: ${{ github.ref_name }}
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
